### ISSUE TITLE
Update to version 2019?

### ISSUE THREAD

**Issue by asuh** [ryanhellyer/end-to-end#2]
End-to-end encryption for WordPress content is a relevant project to continue now more than ever and I think there is a need for something like this. With the rise of various end-to-end solutions like Signal, the potential for publishing secure content is intriguing.

As the plugin already allows, I wouldn't want to use it to encrypt every post I write but there might come times where I'd like 256bit AES encryption from time to time, even to be syndicated to other RSS feeds or applications for real end-to-end communication.

@ryanhellyer Can I nudge you to pick this back up this year? I'd be happy to submit a PR for UI updates and tweaks as well :)

**Comment by ryanhellyer** [comment]
I'm not likely to add any more features to this any time soon. It's still working for the purpose I created it for, and it's unfortunately created too many support requests from people who don't understand how it works.

If you would like to fork it, I'm happy to recommend people switch to your forked version.

**Comment by asuh** [comment]
Right, I can understand where you're coming from. I'm not versed enough with encryption and cryptography to make meaningful changes to what you created but I might fork and update at least from the UI side.

I'm curious, though, if you were to make changes or updates, what would you consider doing to this plugin? It'd be neat to know where you think you'd take it with more motivation.

**Comment by ryanhellyer** [comment]
I probably wouldn't take it much further actually.

I would be more interested in a simpler all-in-one script which stored encrypted files on the internet. Perhaps even using something standard like GitHub as the database backend and having it's encrypted contents publicly available.

For maximum security, it would make sense to implement it as a browser extension. This prevents attacks at server level, or via XSS. If someone can interfere with the website, then they can alter the encryption process and hence access the unencrypted data during the save process. Using a browser extension instead of a publicly accessible website, allows for bypassing that issue.

I mostly use this tool for storing private notes which I don't want to lose. WordPress updates risk accidentally breaking the data saving system, which could theoretically result in the unencrypted version being saved.

**Comment by asuh** [comment]
This is good food for thought, thank you. It makes sense about using device encryption rather than relying on the server. 

The challenge would be a good UX of writing something using WordPress post editor and encrypting it from whatever device is used to write the post, and a browser extension could be a good start. 

I'll have to continue giving this more thought but I'll close this Issue

**Comment by ryanhellyer** [comment]
Ohhh, hang on, there is quite a big problem! I Just realised that the existing functionality has totally broken with the addition of Gutenberg to WordPress core!

**Comment by ryanhellyer** [comment]
Crisis averted. I can bypass that by using the Classic Editor plugin.

This will likely prompt me to do an update as you requested though. I do still use this plugin, and was just not intending to improve it. But having it totally broken is not exactly what I had in mind ;)

**Comment by asuh** [comment]
> For maximum security, it would make sense to implement it as a browser extension. This prevents attacks at server level, or via XSS. If someone can interfere with the website, then they can alter the encryption process and hence access the unencrypted data during the save process.

Would it be a lot of work to relocate the encryption from the server-side to the client-side? Instead of a browser extension doing the heavy lifting of encryption, the WP editor could have an event to fire before publish or saving and/or even completely separate action/button not tied to anything.

I get that XSS, rogue attacks, malicious injection, etc., could compromise this, but at the same time maybe there's a way to have some kind of validation for the encryption code used to encrypt the post and its metadata.

**Comment by ryanhellyer** [comment]
Sorry, I didn't see this until now.

I don't think there is any way to do that with complete security from a basic WordPress website. There is no way to validate the data. A browser extension or standalone app, is still the way I would approach this if I needed extreme security.
